version: '3.4'

services:
  mssql:
    restart: always
    ports:
      - "5533:1433"
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA="Y"
    networks:
      - backend

  template:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=mssql;database=ProjectSetup-LocalDev;User Id=sa;Password=Pass@word;TrustServerCertificate=True
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge 

