version: '3.4'
name: solution-template-ddd

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  template:
    image: ${DOCKER_REGISTRY-}template
    build:
      context: .
      dockerfile: src/Launcher/Dockerfile
    depends_on:
      - mssql
